Implement quote/delim encode settings
commonmind/elm-csv-encode pull request #1
Opened 2022-09-03 20:11 UTC by schoettl

Hi, I recently needed support for some encoding settings. Are you interested to merge and publish my changes?

Basically, `quote` tells if *all* cells should be quoted and `delimiter` changes the delimiter.

If the delimiter appears in a cell value, the cell value is quoted regardless of the `quote` setting.

Many of the visible diffs are whitespace changes after elm reformatted the code.

2022-09-12 04:07 UTC, zenhack requested changes
Sorry for the slow response; thanks for the patch! This looks broadly reasonable, just one minor comment in-line.

2022-09-12 04:07 UTC, zenhack commented on src/Csv/Encode.elm
> +type alias EncodeSettings =
Given that we're already in a module called `Encode`, I think we can just call this `Settings`.

2022-09-12 07:21 UTC, schoettl commented on src/Csv/Encode.elm
> +type alias EncodeSettings =
Right, i changed this.

2022-09-12 23:09 UTC, zenhack commented on src/Csv/Encode.elm
> +defaultEncodeSettings : Settings
This should also probabably just be `defaultSettings`. Otherwise LGTM.

2022-09-13 06:19 UTC, schoettl commented
Maybe I should add some documentation to the type?
And rename `quoted` to `alwaysQuoted`? Because if `not quoted`, encode still quotes if there is a quote in the value (which is good, I think).

2022-09-13 06:34 UTC, zenhack commented
That would be great; if you plan on doing that I'll hold off on merging.

2022-09-13 11:17 UTC, schoettl commented
I added doc and changed the name. I also changed my documentation because we don't want to encourage people to use a multi-character delimiter. But it's possible.

2022-09-13 11:18 UTC, schoettl commented
We could also add different quote character to the settings. But I'll leave that for future, don't need it currently.

2022-09-13 18:53 UTC, merged

2022-09-13 18:53 UTC, zenhack commented
Merged, thanks again!

2022-09-13 19:00 UTC, schoettl commented
Thanks!

2022-09-13 19:04 UTC, zenhack commented
Published as 1.1.0, hasn't shown up on package.elm-lang.org but I assume that's just a caching thing and it will update soon.

FYI, `elm bump` had some complaints about the docs, which I fixed:

- Some of the new exported identifiers weren't listed in `@docs`, so I added them.
- The `@docs` you added in front of the markdown footnote for the RFC is actually incorrect; you're only supposed to list identifiers there. It's fine as-is, and you can see on the package index that the RFC link works correctly.

2022-09-13 19:08 UTC, zenhack commented
Ack, another thing I missed: the `Settings` type was not exposed. Fixed and published as `1.2.0`.